# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-22 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerdigitisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='addhar_no',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
